import { v4 as uuidv4 } from 'uuid';
import { IStore } from '../types/store-types';

export const initialStore: IStore = {
  counter: 100,
  dataFromApi: [],
  orderSize: 6,
  foodCards: {
    cold: [
      {
        id: uuidv4(),
        name: 'Ягненок',
        description: 'Фаршированный гречневой кашей, курагой, апельсином и зеленым яблоком',
        price: 100,
        image: './food1.png',
        weight: '100г',
        numberOfPurchase: 1,
      },
      {
        id: uuidv4(),
        name: 'Индейка',
        description: 'Фаршированный гречневой кашей, курагой, апельсином и зеленым яблоком',
        price: 200,
        image: './food2.png',
        weight: '100г',
        numberOfPurchase: 5,
      },
      {
        id: uuidv4(),
        name: 'Гусь',
        description: 'Фаршированный яблоками',
        price: 300,
        image: './food3.png',
        weight: '100г',
        numberOfPurchase: 0,
      },
      {
        id: uuidv4(),
        name: 'Утка',
        description: 'Фаршированный гречневой кашей, курагой, апельсином и зеленым яблоком',
        price: 400,
        image: './food4.png',
        weight: '100г',
        numberOfPurchase: 0,
      },
      {
        id: uuidv4(),
        name: 'Ягненок',
        description: 'Фаршированная рисом, курагой и айвой',
        price: 500,
        image: './food2.png',
        weight: '100г',
        numberOfPurchase: 0,
      },
      {
        id: uuidv4(),
        name: 'Ягненок',
        description: 'Фаршированный гречневой кашей, курагой, апельсином и зеленым яблоком',
        price: 100,
        image: './food1.png',
        weight: '100г',
        numberOfPurchase: 0,
      },
    ],
    hot: [
      {
        id: uuidv4(),
        name: 'Ягненок',
        description: 'Фаршированный гречневой кашей, курагой, апельсином и зеленым яблоком',
        price: 100,
        image: './food4.png',
        weight: '100г',
        numberOfPurchase: 0,
      },
      {
        id: uuidv4(),
        name: 'Ягненок',
        description: 'Фаршированный гречневой кашей, курагой, апельсином и зеленым яблоком',
        price: 100,
        image: './food1.png',
        weight: '100г',
        numberOfPurchase: 0,
      },
      {
        id: uuidv4(),
        name: 'Ягненок',
        description: 'Фаршированный гречневой кашей, курагой, апельсином и зеленым яблоком',
        price: 100,
        image: './food3.png',
        weight: '100г',
        numberOfPurchase: 0,
      },
      {
        id: uuidv4(),
        name: 'Ягненок',
        description: 'Фаршированный гречневой кашей, курагой, апельсином и зеленым яблоком',
        price: 100,
        image: './food2.png',
        weight: '100г',
        numberOfPurchase: 0,
      },
      {
        id: uuidv4(),
        name: 'Ягненок',
        description: 'Фаршированный гречневой кашей, курагой, апельсином и зеленым яблоком',
        price: 100,
        image: './food3.png',
        weight: '100г',
        numberOfPurchase: 0,
      },
      {
        id: uuidv4(),
        name: 'Ягненок',
        description: 'Фаршированный гречневой кашей, курагой, апельсином и зеленым яблоком',
        price: 100,
        image: './food2.png',
        weight: '100г',
        numberOfPurchase: 0,
      },
      {
        id: uuidv4(),
        name: 'Ягненок',
        description: 'Фаршированный гречневой кашей, курагой, апельсином и зеленым яблоком',
        price: 100,
        image: './food1.png',
        weight: '100г',
        numberOfPurchase: 0,
      },
      {
        id: uuidv4(),
        name: 'Ягненок',
        description: 'Фаршированный гречневой кашей, курагой, апельсином и зеленым яблоком',
        price: 100,
        image: './food4.png',
        weight: '100г',
        numberOfPurchase: 0,
      },
    ],

    meet: [
      {
        id: uuidv4(),
        name: 'Ягненок',
        description: 'Фаршированный гречневой кашей, курагой, апельсином и зеленым яблоком',
        price: 100,
        image: './food3.png',
        weight: '100г',
        numberOfPurchase: 0,
      },
      {
        id: uuidv4(),
        name: 'Ягненок',
        description: 'Фаршированный гречневой кашей, курагой, апельсином и зеленым яблоком',
        price: 100,
        image: './food4.png',
        weight: '100г',
        numberOfPurchase: 0,
      },
      {
        id: uuidv4(),
        name: 'Ягненок',
        description: 'Фаршированный гречневой кашей, курагой, апельсином и зеленым яблоком',
        price: 100,
        image: './food1.png',
        weight: '100г',
        numberOfPurchase: 0,
      },
      {
        id: uuidv4(),
        name: 'Ягненок',
        description: 'Фаршированный гречневой кашей, курагой, апельсином и зеленым яблоком',
        price: 100,
        image: './food2.png',
        weight: '100г',
        numberOfPurchase: 0,
      },
      {
        id: uuidv4(),
        name: 'Ягненок',
        description: 'Фаршированный гречневой кашей, курагой, апельсином и зеленым яблоком',
        price: 100,
        image: './food3.png',
        weight: '100г',
        numberOfPurchase: 0,
      },
      {
        id: uuidv4(),
        name: 'Ягненок',
        description: 'Фаршированный гречневой кашей, курагой, апельсином и зеленым яблоком',
        price: 100,
        image: './food4.png',
        weight: '100г',
        numberOfPurchase: 0,
      },
      {
        id: uuidv4(),
        name: 'Ягненок',
        description: 'Фаршированный гречневой кашей, курагой, апельсином и зеленым яблоком',
        price: 100,
        image: './food1.png',
        weight: '100г',
        numberOfPurchase: 0,
      },

    ],
  },
};
