import { v4 as uuidv4 } from 'uuid';
import { IStore } from '../types/store-types';

const getRandomInt = (min: number, max: number): number => Math.floor(Math.random() * (max - min)) + min;

export const initialStore: IStore = {
  counter: 100,
  dataFromApi: [],
  orderSize: 7,
  foodCards: {
    cold: [
      {
        id: '1',
        name: 'Ягненок',
        description: 'Фаршированный гречневой кашей, курагой, апельсином и зеленым яблоком',
        price: 100,
        image: './food1.png',
        weight: '100г',
        numberOfPurchase: 1,
        protein: getRandomInt(10, 200),
        fat: getRandomInt(10, 200),
        carbohydrates: getRandomInt(10, 200),
        calories: getRandomInt(10, 200),
      },
      {
        id: '2',
        name: 'Индейка',
        description: 'Фаршированный гречневой кашей, курагой, апельсином и зеленым яблоком',
        price: 200,
        image: './food2.png',
        weight: '1000г',
        numberOfPurchase: 5,
        protein: getRandomInt(10, 200),
        fat: getRandomInt(10, 200),
        carbohydrates: getRandomInt(10, 200),
        calories: getRandomInt(10, 200),
      },
      {
        id: '3',
        name: 'Гусь',
        description: 'Фаршированный яблоками',
        price: 300,
        image: './food3.png',
        weight: '10000г',
        numberOfPurchase: 1,
        protein: getRandomInt(10, 200),
        fat: getRandomInt(10, 200),
        carbohydrates: getRandomInt(10, 200),
        calories: getRandomInt(10, 200),
      },
      {
        id: uuidv4(),
        name: 'Утка',
        description: 'Фаршированный гречневой кашей, курагой, апельсином и зеленым яблоком',
        price: 400,
        image: './food4.png',
        weight: '100000г',
        numberOfPurchase: 0,
        protein: getRandomInt(10, 200),
        fat: getRandomInt(10, 200),
        carbohydrates: getRandomInt(10, 200),
        calories: getRandomInt(10, 200),
      },
      {
        id: uuidv4(),
        name: 'Ягненок',
        description: 'Фаршированная рисом, курагой и айвой',
        price: 500,
        image: './food2.png',
        weight: '100г',
        numberOfPurchase: 0,
        protein: getRandomInt(10, 200),
        fat: getRandomInt(10, 200),
        carbohydrates: getRandomInt(10, 200),
        calories: getRandomInt(10, 200),
      },
      {
        id: uuidv4(),
        name: 'Ягненок',
        description: 'Фаршированный гречневой кашей, курагой, апельсином и зеленым яблоком',
        price: 100,
        image: './food1.png',
        weight: '100г',
        numberOfPurchase: 0,
        protein: getRandomInt(10, 200),
        fat: getRandomInt(10, 200),
        carbohydrates: getRandomInt(10, 200),
        calories: getRandomInt(10, 200),
      },
    ],
    hot: [
      {
        id: '111',
        name: 'Ягненок',
        description: 'Фаршированный гречневой кашей, курагой, апельсином и зеленым яблоком',
        price: 100,
        image: './food4.png',
        weight: '100г',
        numberOfPurchase: 0,
        protein: getRandomInt(10, 200),
        fat: getRandomInt(10, 200),
        carbohydrates: getRandomInt(10, 200),
        calories: getRandomInt(10, 200),
      },
      {
        id: '112',
        name: 'Ягненок',
        description: 'Фаршированный гречневой кашей, курагой, апельсином и зеленым яблоком',
        price: 110,
        image: './food1.png',
        weight: '100г',
        numberOfPurchase: 0,
        protein: getRandomInt(10, 200),
        fat: getRandomInt(10, 200),
        carbohydrates: getRandomInt(10, 200),
        calories: getRandomInt(10, 200),
      },
      {
        id: '113',
        name: 'Ягненок',
        description: 'Фаршированный гречневой кашей, курагой, апельсином и зеленым яблоком',
        price: 120,
        image: './food3.png',
        weight: '100г',
        numberOfPurchase: 0,
        protein: getRandomInt(10, 200),
        fat: getRandomInt(10, 200),
        carbohydrates: getRandomInt(10, 200),
        calories: getRandomInt(10, 200),
      },
      {
        id: uuidv4(),
        name: 'Ягненок',
        description: 'Фаршированный гречневой кашей, курагой, апельсином и зеленым яблоком',
        price: 130,
        image: './food2.png',
        weight: '100г',
        numberOfPurchase: 0,
        protein: getRandomInt(10, 200),
        fat: getRandomInt(10, 200),
        carbohydrates: getRandomInt(10, 200),
        calories: getRandomInt(10, 200),
      },
      {
        id: uuidv4(),
        name: 'Ягненок',
        description: 'Фаршированный гречневой кашей, курагой, апельсином и зеленым яблоком',
        price: 140,
        image: './food3.png',
        weight: '100г',
        numberOfPurchase: 0,
        protein: getRandomInt(10, 200),
        fat: getRandomInt(10, 200),
        carbohydrates: getRandomInt(10, 200),
        calories: getRandomInt(10, 200),
      },
      {
        id: uuidv4(),
        name: 'Ягненок',
        description: 'Фаршированный гречневой кашей, курагой, апельсином и зеленым яблоком',
        price: 150,
        image: './food2.png',
        weight: '100г',
        numberOfPurchase: 0,
        protein: getRandomInt(10, 200),
        fat: getRandomInt(10, 200),
        carbohydrates: getRandomInt(10, 200),
        calories: getRandomInt(10, 200),
      },
      {
        id: uuidv4(),
        name: 'Ягненок',
        description: 'Фаршированный гречневой кашей, курагой, апельсином и зеленым яблоком',
        price: 160,
        image: './food1.png',
        weight: '100г',
        numberOfPurchase: 0,
        protein: getRandomInt(10, 200),
        fat: getRandomInt(10, 200),
        carbohydrates: getRandomInt(10, 200),
        calories: getRandomInt(10, 200),
      },
      {
        id: uuidv4(),
        name: 'Ягненок',
        description: 'Фаршированный гречневой кашей, курагой, апельсином и зеленым яблоком',
        price: 170,
        image: './food4.png',
        weight: '100г',
        numberOfPurchase: 0,
        protein: getRandomInt(10, 200),
        fat: getRandomInt(10, 200),
        carbohydrates: getRandomInt(10, 200),
        calories: getRandomInt(10, 200),
      },
    ],

    meet: [
      {
        id: uuidv4(),
        name: 'Ягненок',
        description: 'Фаршированный гречневой кашей, курагой, апельсином и зеленым яблоком',
        price: 180,
        image: './food3.png',
        weight: '100г',
        numberOfPurchase: 0,
        protein: getRandomInt(10, 200),
        fat: getRandomInt(10, 200),
        carbohydrates: getRandomInt(10, 200),
        calories: getRandomInt(10, 200),
      },
      {
        id: uuidv4(),
        name: 'Ягненок',
        description: 'Фаршированный гречневой кашей, курагой, апельсином и зеленым яблоком',
        price: 190,
        image: './food4.png',
        weight: '100г',
        numberOfPurchase: 0,
        protein: getRandomInt(10, 200),
        fat: getRandomInt(10, 200),
        carbohydrates: getRandomInt(10, 200),
        calories: getRandomInt(10, 200),
      },
      {
        id: uuidv4(),
        name: 'Ягненок',
        description: 'Фаршированный гречневой кашей, курагой, апельсином и зеленым яблоком',
        price: 200,
        image: './food1.png',
        weight: '100г',
        numberOfPurchase: 0,
        protein: getRandomInt(10, 200),
        fat: getRandomInt(10, 200),
        carbohydrates: getRandomInt(10, 200),
        calories: getRandomInt(10, 200),
      },
      {
        id: uuidv4(),
        name: 'Ягненок',
        description: 'Фаршированный гречневой кашей, курагой, апельсином и зеленым яблоком',
        price: 210,
        image: './food2.png',
        weight: '100г',
        numberOfPurchase: 0,
        protein: getRandomInt(10, 200),
        fat: getRandomInt(10, 200),
        carbohydrates: getRandomInt(10, 200),
        calories: getRandomInt(10, 200),
      },
      {
        id: uuidv4(),
        name: 'Ягненок',
        description: 'Фаршированный гречневой кашей, курагой, апельсином и зеленым яблоком',
        price: 220,
        image: './food3.png',
        weight: '100г',
        numberOfPurchase: 0,
        protein: getRandomInt(10, 200),
        fat: getRandomInt(10, 200),
        carbohydrates: getRandomInt(10, 200),
        calories: getRandomInt(10, 200),
      },
      {
        id: uuidv4(),
        name: 'Ягненок',
        description: 'Фаршированный гречневой кашей, курагой, апельсином и зеленым яблоком',
        price: 230,
        image: './food4.png',
        weight: '100г',
        numberOfPurchase: 0,
        protein: getRandomInt(10, 200),
        fat: getRandomInt(10, 200),
        carbohydrates: getRandomInt(10, 200),
        calories: getRandomInt(10, 200),
      },
      {
        id: uuidv4(),
        name: 'Ягненок',
        description: 'Фаршированный гречневой кашей, курагой, апельсином и зеленым яблоком',
        price: 240,
        image: './food1.png',
        weight: '100г',
        numberOfPurchase: 0,
        protein: getRandomInt(10, 200),
        fat: getRandomInt(10, 200),
        carbohydrates: getRandomInt(10, 200),
        calories: getRandomInt(10, 200),
      },

    ],
  },
};
