import { IStore } from '../types/store-types';

export const initialStore: IStore = {
  counter: 100,
  dataFromApi: [],
  foodCards: {
    cold: [
      {
        id: 1,
        name: 'Ягненок',
        description: 'Фаршированный гречневой кашей, курагой, апельсином и зеленым яблоком',
        price: 100,
        image: './food1.png',
        weight: '100г',
        numberOfPurchase: 1,
      },
      {
        id: 11,
        name: 'Индейка',
        description: 'Фаршированный гречневой кашей, курагой, апельсином и зеленым яблоком',
        price: 200,
        image: './food2.png',
        weight: '100г',
        numberOfPurchase: 5,
      },
      {
        id: 111,
        name: 'Гусь',
        description: 'Фаршированный яблоками',
        price: 300,
        image: './food3.png',
        weight: '100г',
        numberOfPurchase: 0,
      },
      {
        id: 11111,
        name: 'Утка',
        description: 'Фаршированный гречневой кашей, курагой, апельсином и зеленым яблоком',
        price: 400,
        image: './food4.png',
        weight: '100г',
        numberOfPurchase: 0,
      },
      {
        id: 111111,
        name: 'Ягненок',
        description: 'Фаршированная рисом, курагой и айвой',
        price: 500,
        image: './food2.png',
        weight: '100г',
        numberOfPurchase: 0,
      },
      {
        id: 1111111,
        name: 'Ягненок',
        description: 'Фаршированный гречневой кашей, курагой, апельсином и зеленым яблоком',
        price: 100,
        image: './food1.png',
        weight: '100г',
        numberOfPurchase: 0,
      },
    ],
    hot: [
      {
        id: 2,
        name: 'Ягненок',
        description: 'Фаршированный гречневой кашей, курагой, апельсином и зеленым яблоком',
        price: 100,
        image: './food4.png',
        weight: '100г',
        numberOfPurchase: 0,
      },
      {
        id: 22,
        name: 'Ягненок',
        description: 'Фаршированный гречневой кашей, курагой, апельсином и зеленым яблоком',
        price: 100,
        image: './food1.png',
        weight: '100г',
        numberOfPurchase: 0,
      },
      {
        id: 222,
        name: 'Ягненок',
        description: 'Фаршированный гречневой кашей, курагой, апельсином и зеленым яблоком',
        price: 100,
        image: './food3.png',
        weight: '100г',
        numberOfPurchase: 0,
      },
      {
        id: 2222,
        name: 'Ягненок',
        description: 'Фаршированный гречневой кашей, курагой, апельсином и зеленым яблоком',
        price: 100,
        image: './food2.png',
        weight: '100г',
        numberOfPurchase: 0,
      },
      {
        id: 22222,
        name: 'Ягненок',
        description: 'Фаршированный гречневой кашей, курагой, апельсином и зеленым яблоком',
        price: 100,
        image: './food3.png',
        weight: '100г',
        numberOfPurchase: 0,
      },
      {
        id: 222222,
        name: 'Ягненок',
        description: 'Фаршированный гречневой кашей, курагой, апельсином и зеленым яблоком',
        price: 100,
        image: './food2.png',
        weight: '100г',
        numberOfPurchase: 0,
      },
      {
        id: 2222222,
        name: 'Ягненок',
        description: 'Фаршированный гречневой кашей, курагой, апельсином и зеленым яблоком',
        price: 100,
        image: './food1.png',
        weight: '100г',
        numberOfPurchase: 0,
      },
      {
        id: 222222222,
        name: 'Ягненок',
        description: 'Фаршированный гречневой кашей, курагой, апельсином и зеленым яблоком',
        price: 100,
        image: './food4.png',
        weight: '100г',
        numberOfPurchase: 0,
      },
    ],

    meet: [
      {
        id: 3,
        name: 'Ягненок',
        description: 'Фаршированный гречневой кашей, курагой, апельсином и зеленым яблоком',
        price: 100,
        image: './food3.png',
        weight: '100г',
        numberOfPurchase: 0,
      },
      {
        id: 33,
        name: 'Ягненок',
        description: 'Фаршированный гречневой кашей, курагой, апельсином и зеленым яблоком',
        price: 100,
        image: './food4.png',
        weight: '100г',
        numberOfPurchase: 0,
      },
      {
        id: 333,
        name: 'Ягненок',
        description: 'Фаршированный гречневой кашей, курагой, апельсином и зеленым яблоком',
        price: 100,
        image: './food1.png',
        weight: '100г',
        numberOfPurchase: 0,
      },
      {
        id: 3333,
        name: 'Ягненок',
        description: 'Фаршированный гречневой кашей, курагой, апельсином и зеленым яблоком',
        price: 100,
        image: './food2.png',
        weight: '100г',
        numberOfPurchase: 0,
      },
      {
        id: 33333,
        name: 'Ягненок',
        description: 'Фаршированный гречневой кашей, курагой, апельсином и зеленым яблоком',
        price: 100,
        image: './food3.png',
        weight: '100г',
        numberOfPurchase: 0,
      },
      {
        id: 333333,
        name: 'Ягненок',
        description: 'Фаршированный гречневой кашей, курагой, апельсином и зеленым яблоком',
        price: 100,
        image: './food4.png',
        weight: '100г',
        numberOfPurchase: 0,
      },
      {
        id: 3333333,
        name: 'Ягненок',
        description: 'Фаршированный гречневой кашей, курагой, апельсином и зеленым яблоком',
        price: 100,
        image: './food1.png',
        weight: '100г',
        numberOfPurchase: 0,
      },

    ],
  },
};
