export enum Actions {
  ADDGOODSINCART = "ADDGOODSINCART",
  DECREASE_GOODSINCART = "DECREASE_GOODSINCART",
  DELETE_FOOD_FROM_CART = "DELETE_FOOD_FROM_CART",
  TOGGLE_MODAL = "TOGGLE_MODAL",
  CLOSE_MODAL = "CLOSE_MODAL",
}
